AllCops:
  RunRailsCops: true

Style/AlignParameters:
  # Disable, till rubocop supports combination of styles.
  # Use one of this styles where appropriate, keep it clean, compact and readable.
  Enabled: false
  EnforcedStyle:
  - aligned
  - with_fixed_indentation
Style/ClosingParenthesisIndentation: {Enabled: false}
Style/Documentation: {Enabled: false}
Style/DotPosition: {EnforcedStyle: trailing}
Style/IfUnlessModifier: {Enabled: false}
Style/ModuleFunction: {Enabled: false}
Style/MultilineOperationIndentation: {EnforcedStyle: indented}
Style/PredicateName: {Enabled: false}
Style/SignalException: {EnforcedStyle: only_raise}
Style/SpaceInsideHashLiteralBraces: {EnforcedStyle: no_space}
Style/TrailingComma: {Enabled: false}

Metrics/AbcSize: {Max: 21}
Metrics/LineLength: {Max: 100}
Metrics/MethodLength: {Max: 30}
